### ISSUE TITLE
Acabar el juego!

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s2-evaluacion-intermedia-mariavioleta1417#1]
Buen trabajo María!! Casi tienes el juego acabado, te paso algunas sugerencias con cosicas a mejorar:

- El HTML está chachi pero hay que cuidar los detalles: si ponemos un label con un for, necesitamos un input con un id que tenga el mismo valor que el for, así indicamos que están conectados.
- Tienes dos archivos main.js, ¿que te parece si movemos el que has usado a la carpeta js para que nos quede más organizadito?
- Si mueves la declaración de tus variables al inicio del scope, mejor que mejor.
- Grande esa lógica, ¿te animas con el contador? Si tienes dudas ya sabes preguntame sin problema.

A por ello!

**Comment by mariavioleta1417** [comment]
creo que ya está, en vez de contador hice que con cada click cambiara en color de fondo y después se me fue un poquito de las manos🦄🦄🦄

**Comment by nasivuela** [comment]
Se me olvidó cerrar, este ejercicio esta más allá del deber ;)
